import numpy as np

#IAU 2015
MARS_EQUATORIAL_RADIUS = 3396190.0  
MARS_POLAR_RADIUS = 3376200.0       
MARS_FLATTENING = (MARS_EQUATORIAL_RADIUS - MARS_POLAR_RADIUS) / MARS_EQUATORIAL_RADIUS
MARS_ECCENTRICITY_SQUARED = 2 * MARS_FLATTENING - MARS_FLATTENING**2

# Sharad parameters
FREQ_MIN = 15e6          
FREQ_MAX = 25e6          
FREQ_CENTER = 20e6       
BANDWIDTH = 10e6         
SPEED_OF_LIGHT = 299792458.0  
WAVELENGTH = SPEED_OF_LIGHT / FREQ_CENTER
PULSE_DURATION = 85e-6   
PRF = 700.0             
SAMPLE_INTERVAL = 37.5e-9  
RANGE_RESOLUTION_AIR = SPEED_OF_LIGHT * SAMPLE_INTERVAL / 2  # 5.625 m
SAR_ALONG_TRACK_RESOLUTION = 300.0
CROSS_TRACK_RESOLUTION = np.inf 
# CROSS_TRACK_RESOLUTION = 120000.0 


#Simulation Parameters 
FACET_SIZE_CROSS_TRACK = 30.0
FACET_SIZE_ALONG_TRACK = 300.0  
CROSS_TRACK_EXTENT = 45000.0 
MAX_TIME_DELAY = 135e-6        
MAX_INCIDENCE_ANGLE = 85.0

# DEM PARAMETERS
MOLA_PIXELS_PER_DEGREE = 128     
MOLA_UNRELIABLE_LATITUDE = 87.1
APPLY_DEM_FILTER = True
DEM_FILTER_SIGMA = 2.0  

# CLUTTERGRAM PARAMETERS
N_TIME_BINS = int(MAX_TIME_DELAY / SAMPLE_INTERVAL)  # 3600 bins
NORMALIZATION_METHOD = 'dB' 
DB_DYNAMIC_RANGE = 80.0          

# Number of facets per spacecraft position
N_FACETS_PER_POSITION = int(2 * CROSS_TRACK_EXTENT / FACET_SIZE_CROSS_TRACK)

# FILE PATHS
DATA_DIR = '../data'
SHARAD_DIR = f'{DATA_DIR}/sharad'
MOLA_DIR = f'{DATA_DIR}/mola'
OUTPUT_DIR = f'{DATA_DIR}/outputs'

print(f"Configuration loaded:")
print(f"  Wavelength: {WAVELENGTH:.2f} m")
print(f"  Range resolution: {RANGE_RESOLUTION_AIR:.2f} m")
print(f"  Facets per position: {N_FACETS_PER_POSITION}")
print(f"  Time bins: {N_TIME_BINS}")